// Auto-generated by QA Tool — do not edit manually
const { defineConfig } = require('@playwright/test');
module.exports = defineConfig({
  testDir:       './tests',
  timeout:       25000,
  retries:       0,
  workers:       3,
  fullyParallel: true,
  reporter: [['json', { outputFile: 'test-results/results.json' }], ['list']],
  use: {
    screenshot:        'only-on-failure',
    video:             'off',
    trace:             'off',
    actionTimeout:     10000,
    navigationTimeout: 15000,
    ignoreHTTPSErrors: true,
  },
  projects: [
    { name: 'chromium',      use: { browserName: 'chromium', viewport: { width: 1280, height: 720 } } }
  ],
  outputDir: 'test-results/artifacts',
});
